In [2]:
import numpy as np
from scipy.stats import stats

In [35]:
N = 10
x1 = np.random.randn(N)
x2 = x1 + np.random.randn(N)
x3 = np.random.randn(N) + 4
x4 = x2*np.random.randn(N)

m1 = np.mean(x1)
m2 = np.mean(x2)
m3 = np.mean(x3)
m4 = np.mean(x4)

s1 = np.std(x1,ddof=1)
s2 = np.std(x2,ddof=1)
s3 = np.std(x3,ddof=1)
s4 = np.std(x4,ddof=1)

s = np.array([s1,s2,s3,s4])

In [36]:
data = np.array([x1,x2,x3,x4]).T

In [37]:
R = np.corrcoef(data.T)
C = np.cov(data.T)
print(R)
print(C)

[[ 1.          0.88510527  0.36983365 -0.15992269]
 [ 0.88510527  1.          0.08292608 -0.38631218]
 [ 0.36983365  0.08292608  1.          0.36297881]
 [-0.15992269 -0.38631218  0.36297881  1.        ]]
[[ 0.93502095  1.35604389  0.34765576 -0.07340721]
 [ 1.35604389  2.51036167  0.12772962 -0.29055243]
 [ 0.34765576  0.12772962  0.94507151  0.16750647]
 [-0.07340721 -0.29055243  0.16750647  0.22533878]]


In [38]:
S = np.zeros((4,4))

for i, row in enumerate(S):
    
    S[i][i] = s[i]

##### Testing that C = SRS

In [39]:
C_computed = S @ R @ S

In [40]:
C, C_computed

(array([[ 0.93502095,  1.35604389,  0.34765576, -0.07340721],
        [ 1.35604389,  2.51036167,  0.12772962, -0.29055243],
        [ 0.34765576,  0.12772962,  0.94507151,  0.16750647],
        [-0.07340721, -0.29055243,  0.16750647,  0.22533878]]),
 array([[ 0.93502095,  1.35604389,  0.34765576, -0.07340721],
        [ 1.35604389,  2.51036167,  0.12772962, -0.29055243],
        [ 0.34765576,  0.12772962,  0.94507151,  0.16750647],
        [-0.07340721, -0.29055243,  0.16750647,  0.22533878]]))